version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - REACT_APP_API_BASE_URL=http://server:5000/api
        depends_on:
            - server
        networks:
            - app-network

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        environment:
            - NODE_ENV=production
            - MONGODB_URI=mongodb://mongo:27017/learn_czech
            - JWT_SECRET=${JWT_SECRET}
            - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
            - TOKEN_EXPIRY=1h
            - REFRESH_TOKEN_EXPIRY=7d
        depends_on:
            - mongo
        networks:
            - app-network

    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongo_data:
