version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        depends_on:
            - server
            - mongo

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        environment:
            - NODE_ENV=production
            - MONGODB_URI=mongodb://mongo:27017/duolingo_clone
            - JWT_SECRET=your_jwt_secret_here
        depends_on:
            - mongo

    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
