version: '3.8'

services:
    backend:
        image: extender777/czech-backend
        ports:
            - '6004:5000'
        environment:
            - NODE_ENV=production
            - MONGODB_URI=mongodb://mongodb:27017/learn_czech
            - JWT_SECRET=${JWT_SECRET}
        restart: unless-stopped
        depends_on:
            - mongodb

    frontend:
        image: extender777/czech-frontend
        environment:
            - NODE_ENV=production
        ports:
            - '8686:80'
        restart: unless-stopped
        depends_on:
            - backend
        logging:
            driver: none

    mongodb:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        restart: unless-stopped
        logging:
            driver: none

volumes:
    mongo-data:
